/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Guru;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import login.KoneksiDB;

/**
 *
 * @author LENOVO
 */
public class Data_siswa extends javax.swing.JFrame {
 Connection conn=null;
        ResultSet rs=null;
        PreparedStatement pst=null;
        int curRow=0;
    /**
     * Creates new form Data_siswa
     */
    public Data_siswa() {
        initComponents();
         this.setLocationRelativeTo(null);// center form in the screen
           conn=KoneksiDB.getKoneksi();
           tabelsiswa();
           tabel();
    }
  void searchsiswa (){
        DefaultTableModel tbl = new DefaultTableModel();
        tbl.addColumn("nis");
        tbl.addColumn("nama siswa");
        tbl.addColumn("alamat");
        tbl.addColumn("no telp");
        tbl.addColumn("tingkat");
         tbl.addColumn("jurusan");
        
        try {
            String sql = "SELECT * FROM siswa INNER JOIN jurusan ON siswa.kode_jurusan=jurusan.kode_jurusan WHERE nama_siswa LIKE '%" + searchsiswa.getText() +  "%'";
            Connection con = (Connection) KoneksiDB.getKoneksi();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            
            while(rs.next()){
                tbl.addRow(new Object[] {
                    rs.getString("NIS"),
                    rs.getString("nama_siswa"),
                    rs.getString("alamat"),
                    rs.getString("no_telp"),
                     rs.getString("tingkat"),
                     rs.getString("jurusan"),

                });
                tbsiswa.setModel(tbl);
            }
            
        } catch (Exception e) {
            System.out.println(e);
        }
    }

 public void tabelsiswa(){
        DefaultTableModel tbl = new DefaultTableModel();
        tbl.addColumn("nis");
        tbl.addColumn("nama siswa");
        tbl.addColumn("alamat");
        tbl.addColumn("no telp");
       
         tbl.addColumn("tingkat");
        tbl.addColumn("jurusan");
        
         tbl.getDataVector().removeAllElements();
        tbl.fireTableDataChanged();
        
        try {
            String sql = "SELECT * FROM siswa INNER JOIN jurusan ON siswa.kode_jurusan=jurusan.kode_jurusan";
            Connection con = (Connection) KoneksiDB.getKoneksi();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            
            while(rs.next()){
                tbl.addRow(new Object[] {
                    rs.getString("NIS"),
                    rs.getString("nama_siswa"),
                    rs.getString("alamat"),
                    rs.getString("no_telp"),
                     
                     rs.getString("tingkat"),
                      rs.getString("jurusan"),

                });
                
                tbsiswa.setModel(tbl);
              
                
            }
            
        } catch (Exception e) {
            System.out.println(e);
        }
 }  
        public void tabel(){
        DefaultTableModel tbl = new DefaultTableModel();
      
          tbl.addColumn("kode jurusan");
         tbl.addColumn("tingkat");
        tbl.addColumn("jurusan");
         tbl.getDataVector().removeAllElements();
        tbl.fireTableDataChanged();
        try {
            String sql = "SELECT * FROM jurusan";
            Connection con = (Connection) KoneksiDB.getKoneksi();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            
            while(rs.next()){
                tbl.addRow(new Object[] {
                   rs.getString("kode_jurusan"),
                     rs.getString("tingkat"),
                      rs.getString("jurusan"),

                });
                
            
              kdjurusan.addItem(rs.getString("kode_jurusan"));
                
            }
            
        } catch (Exception e) {
            System.out.println(e);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        searchsiswa = new javax.swing.JTextField();
        NIS = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        namasiswa = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        editsiswa = new javax.swing.JButton();
        telpsiswa = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        tambahsiswa = new javax.swing.JButton();
        carisiswa = new javax.swing.JButton();
        almt = new javax.swing.JTextField();
        hapussiswa = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbsiswa = new javax.swing.JTable();
        jurusan = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        tingkat = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        kdjurusan = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 255, 153));

        jLabel21.setForeground(new java.awt.Color(0, 0, 0));
        jLabel21.setText("alamat");

        searchsiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchsiswaActionPerformed(evt);
            }
        });

        jLabel22.setForeground(new java.awt.Color(0, 0, 0));
        jLabel22.setText("NIS");

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 0));
        jLabel20.setText("DATA SISWA");

        jLabel23.setForeground(new java.awt.Color(0, 0, 0));
        jLabel23.setText("nama_siswa");

        editsiswa.setText("edit");
        editsiswa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editsiswaMouseClicked(evt);
            }
        });
        editsiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editsiswaActionPerformed(evt);
            }
        });

        jLabel24.setForeground(new java.awt.Color(0, 0, 0));
        jLabel24.setText("no_telp");

        tambahsiswa.setText("Tambah");
        tambahsiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahsiswaActionPerformed(evt);
            }
        });

        carisiswa.setText("cari");
        carisiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carisiswaActionPerformed(evt);
            }
        });

        hapussiswa.setText("hapus");
        hapussiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapussiswaActionPerformed(evt);
            }
        });

        tbsiswa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "nis", "nama siswa", "no telp", "alamat", "kode jurusan", "tingkat", "jurusan"
            }
        ));
        tbsiswa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbsiswaMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbsiswa);

        jLabel25.setForeground(new java.awt.Color(0, 0, 0));
        jLabel25.setText("tingkat");

        jLabel26.setForeground(new java.awt.Color(0, 0, 0));
        jLabel26.setText("jurusan");

        jLabel27.setForeground(new java.awt.Color(0, 0, 0));
        jLabel27.setText("kode_jurusan");

        kdjurusan.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                kdjurusanPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        kdjurusan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kdjurusanMouseClicked(evt);
            }
        });
        kdjurusan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kdjurusanActionPerformed(evt);
            }
        });

        jButton1.setText("kembali");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel20)
                        .addGap(212, 212, 212))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(69, 69, 69)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(NIS, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(namasiswa, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(103, 103, 103))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(197, 197, 197)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel22)
                                    .addComponent(jLabel23)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(tambahsiswa, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(164, 164, 164)
                                        .addComponent(editsiswa, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel24)
                                .addGap(57, 57, 57)
                                .addComponent(telpsiswa, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel21)
                                    .addComponent(jLabel27))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(almt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(hapussiswa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(kdjurusan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel25)
                    .addComponent(jLabel26))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchsiswa, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jurusan, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tingkat, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(carisiswa))
                .addGap(16, 16, 16))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel20))
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(telpsiswa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24)
                    .addComponent(NIS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22)
                    .addComponent(jLabel25)
                    .addComponent(tingkat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(almt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21)
                    .addComponent(namasiswa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23)
                    .addComponent(jLabel26)
                    .addComponent(jurusan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(kdjurusan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchsiswa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(carisiswa)
                    .addComponent(hapussiswa)
                    .addComponent(editsiswa)
                    .addComponent(tambahsiswa))
                .addGap(35, 35, 35)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void editsiswaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editsiswaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_editsiswaMouseClicked

    private void editsiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editsiswaActionPerformed
        // TODO add your handling code here:
       try {
            String sql = "UPDATE siswa SET NIS='"+NIS.getText()+"',nama_siswa='"+namasiswa.getText()
                    +"',alamat='"+ almt.getText()+"',no_telp='"+telpsiswa.getText()+"',kode_jurusan='"+kdjurusan.getSelectedItem()+"'WHERE NIS='"+NIS.getText()+"'";
                    
            Connection con = (Connection) KoneksiDB.getKoneksi();
            PreparedStatement pst = con.prepareStatement(sql);  
            pst.execute();
            JOptionPane.showMessageDialog(null, "Berhasil megubah data siswa");
            tabelsiswa();
        } catch (Exception e) {
        
    }        
    }//GEN-LAST:event_editsiswaActionPerformed

    private void tambahsiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahsiswaActionPerformed
        // TODO add your handling code here:

        try {
           
           PreparedStatement stmt = conn.prepareStatement("INSERT INTO siswa (nis, nama_siswa,  no_telp, alamat, kode_jurusan) values (?,?,?,?,?)");
            stmt.setString(1, NIS.getText());
            stmt.setString(2, namasiswa.getText());
            stmt.setString(3,telpsiswa.getText());
            stmt.setString(4, almt.getText());
            stmt.setString(5, (String) kdjurusan.getSelectedItem());
       
            stmt.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data berhasil disimpan", "Pesan", JOptionPane.INFORMATION_MESSAGE);
            tabelsiswa();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal Menambahkan" + e.getMessage());

        }
    }//GEN-LAST:event_tambahsiswaActionPerformed

    private void carisiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carisiswaActionPerformed
        // TODO add your handling code here
        searchsiswa();
    }//GEN-LAST:event_carisiswaActionPerformed

    private void hapussiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapussiswaActionPerformed
        // TODO add your handling code here:

        try {
            String sql = "DELETE FROM siswa WHERE NIS =' " + NIS.getText() + " ' ";

            Connection con = (Connection) KoneksiDB.getKoneksi();
            PreparedStatement pst = con.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Berhasil menghapus data siswa");
            tabelsiswa();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_hapussiswaActionPerformed

    private void kdjurusanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kdjurusanActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_kdjurusanActionPerformed

    private void kdjurusanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kdjurusanMouseClicked
        // TODO add your handling code here:
        
           
    }//GEN-LAST:event_kdjurusanMouseClicked

    private void tbsiswaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbsiswaMouseClicked
        
          int baris = tbsiswa.rowAtPoint(evt.getPoint());
        String a = tbsiswa.getValueAt(baris, 0).toString();
        NIS.setText(a);
        String namaguru = tbsiswa.getValueAt(baris, 1).toString();
        namasiswa.setText(namaguru);
         String telp = tbsiswa.getValueAt(baris, 2).toString();
        almt.setText(telp);
        String almts = tbsiswa.getValueAt(baris, 3).toString();
        telpsiswa.setText(almts);
       
      
        String te = tbsiswa.getValueAt(baris, 4).toString();
        tingkat.setText(te);
        String t = tbsiswa.getValueAt(baris, 5).toString();
        jurusan.setText(t);
      
    }//GEN-LAST:event_tbsiswaMouseClicked

    private void searchsiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchsiswaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchsiswaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
         this.dispose();
            guru ea = new guru();
                     ea.setVisible(true);
                     ea.pack();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void kdjurusanPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_kdjurusanPopupMenuWillBecomeInvisible
        // TODO add your handling code here:
          String item = (String) kdjurusan.getSelectedItem();
        String sql = "select * from jurusan where kode_jurusan = ?";
        try {
            pst = conn.prepareStatement(sql);
            pst.setString(1, item);
            rs =pst.executeQuery();
        
           
            
            
          if(rs.next()){
               
             String nm = rs.getString("tingkat");
                tingkat.setText(nm);
                 String nam = rs.getString("jurusan");
                jurusan.setText(nam);
                
          }
            
           
            
        } catch (Exception e) {
              JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_kdjurusanPopupMenuWillBecomeInvisible

   
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Data_siswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Data_siswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Data_siswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Data_siswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Data_siswa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField NIS;
    private javax.swing.JTextField almt;
    private javax.swing.JButton carisiswa;
    private javax.swing.JButton editsiswa;
    private javax.swing.JButton hapussiswa;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jurusan;
    private javax.swing.JComboBox<String> kdjurusan;
    private javax.swing.JTextField namasiswa;
    private javax.swing.JTextField searchsiswa;
    private javax.swing.JButton tambahsiswa;
    private javax.swing.JTable tbsiswa;
    private javax.swing.JTextField telpsiswa;
    private javax.swing.JTextField tingkat;
    // End of variables declaration//GEN-END:variables
}
